spring.application.name=wallet-service

spring.datasource.username=wallet_user
spring.datasource.password=wallet_password
spring.datasource.url=jdbc:postgresql://localhost:5433/wallet_db
spring.datasource.driver-class-name=org.postgresql.Driver

spring.flyway.enabled=true